[package]
name = "r2024-12-27-clidle"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
eframe = "0.30.0"
egui = "0.30.0"
egui_extras = "0.30.0"
env_logger = "0.11.6"

[features]
persistence = []
